name: 🐞 Bug Report
description: Create a report about something that is not working
labels: ["bug"]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true

  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: |
        Steps to reproduce the behavior.
      placeholder: |
        1. Run command '...'
        2. See error
    validations:
      required: false

  - type: textarea
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Exceptions (if any)
      description: Include the exception you get when facing this issue.
    validations:
      required: false

  - type: input
    attributes:
      label: Reshape Version
      description: Run `reshape --version` (if applicable)
      placeholder: e.g., v0.1.0
    validations:
      required: false

  - type: textarea
    attributes:
      label: Anything else?
      description: |
        - OS and version:
        - IDE you're running on:

        Links? References? Anything that will give us more context!
