name: 🐛 Bug Report
description: Report a bug or unexpected behavior in Reshape
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us investigate.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. Click on '...'
        3. Enter '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what you expected...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - CLI
        - Web UI
        - Both
        - Not sure
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Reshape Version
      description: What version of Reshape are you using? (Run `reshape --version` or check About in Web UI)
      placeholder: e.g., v0.1.0
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What OS are you running Reshape on?
      options:
        - Windows
        - Linux
        - macOS
        - Other
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: OS Version
      description: Specific OS version (e.g., Windows 11, Ubuntu 22.04, macOS 14.2)
      placeholder: e.g., Windows 11 23H2
    validations:
      required: false

  - type: input
    id: dotnet-version
    attributes:
      label: .NET Version (if applicable)
      description: If running from source, what .NET version? (Run `dotnet --version`)
      placeholder: e.g., 10.0.0
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Error Logs/Stack Trace
      description: If applicable, paste any error messages or stack traces
      placeholder: Paste error logs here...
      render: shell
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the problem
      placeholder: Drag and drop images here or paste image URLs
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context about the problem (file types, number of files, special characters in filenames, etc.)
      placeholder: Add any other relevant information...
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this hasn't been reported before
          required: true
        - label: I have provided all required information above
          required: true
        - label: I am using the latest version of Reshape (or have specified my version)
          required: true
